version: "3"
services:
  furbot:
    image: ghcr.io/tekofx/furbot
    container_name: furbot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data/servers:/bot/data/servers

  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: furbot_db
    restart: unless-stopped
    environment:
      TZ: "Europe/Madrid"
      MYSQL_DATABASE: "database"
      MYSQL_USER: "user"
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_PASSWORD: "password"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
