version: '1'
services:
  furbot:
    build: .
    image: furbot
    container_name: furbot
    ports:
      - "100:80"

    volumes:
      - /home/teko/bots/furbot/files:/bot/files/
      - /home/teko/bots/furbot/src:/bot/src
      - /home/teko/bots/furbot/databases:/bot/databases
    restart: unless-stopped
