version: '1'
services:
  furbot:
    image: furbot
    container_name: furbot
    ports:
      - "100:80"

    volumes:
      - ./files:/bot/files/
      - ./databases:/bot/databases
      - ./env:/bot/env

    restart: unless-stopped
