version: '3'
services:
  furbot:
    image: ghcr.io/tekofx/furbot
    container_name: furbot
    ports:
      - "100:80"

    volumes:
      - ./env:/bot/env
      - ./data/servers:/bot/data/servers

    restart: unless-stopped
